import { CardEffect } from "./types";

export const DEFAULT_EFFECTS: CardEffect[] = [
  {
    key: "hakase",
    label: "博士の研究",
    short: "博士",
    mode: "discard",
    draw: 7,
    compress: 0,
    description: "手札を捨て山札から7枚引く",
    imageUrl: "https://www.pokemon-card.com/assets/images/card_images/large/S6a/045454_T_HAKASENO_KENKYU_MAGNOLIA.jpg",
    builtin: true,
  },
  {
    key: "lillie_strong",
    label: "リーリエの決心強",
    short: "リ強",
    mode: "shuffle",
    draw: 8,
    compress: 0,
    description: "手札を山札に戻し8枚引く",
    imageUrl: "https://www.pokemon-card.com/assets/images/card_images/large/M1L/048448_T_RIRIENOKESSHIN.jpg",
    builtin: true,
  },
  {
    key: "lillie_weak",
    label: "リーリエの決心弱",
    short: "リ弱",
    mode: "shuffle",
    draw: 6,
    compress: 0,
    description: "手札を山札に戻し6枚引く",
    imageUrl: "https://www.pokemon-card.com/assets/images/card_images/large/M2a/048697_T_RIRIENOKESSHIN.jpg",
    builtin: true,
  },
  {
    key: "unfair5",
    label: "アンフェアスタンプ (5枚)",
    short: "不5",
    mode: "shuffle",
    draw: 5,
    compress: 0,
    description: "手札を山札に戻し5枚引く",
    imageUrl: "https://www.pokemon-card.com/assets/images/card_images/large/MC/049349_T_ANFUEASUTANPU.jpg",
    builtin: true,
  },
  {
    key: "unfair2",
    label: "アンフェアスタンプ (2枚)",
    short: "不2",
    mode: "shuffle",
    draw: 2,
    compress: 0,
    description: "手札を山札に戻し2枚引く",
    imageUrl: "https://www.pokemon-card.com/assets/images/card_images/large/MC/049349_T_ANFUEASUTANPU.jpg",
    builtin: true,
  },
  {
    key: "redcard",
    label: "スペシャルレッドカード",
    short: "赤",
    mode: "bottom",
    draw: 3,
    compress: 0,
    description: "手札を山札の下に戻し3枚引く",
    imageUrl: "https://www.pokemon-card.com/assets/images/card_images/large/M4/050156_T_SUPESHIXYARUREDDOKADO.jpg",
    builtin: true,
  },
  {
    key: "sakateni",
    label: "さかてにとる (3枚)",
    short: "逆3",
    mode: "draw",
    draw: 3,
    compress: 0,
    description: "山札を3枚引く",
    imageUrl: "https://www.pokemon-card.com/assets/images/card_images/large/SV6a/046066_P_KICHIKIGISUEX.jpg",
    builtin: true,
  },
  {
    key: "dash",
    label: "お使いダッシュ (2枚)",
    short: "走2",
    mode: "draw",
    draw: 2,
    compress: 0,
    description: "山札を2枚引く",
    imageUrl: "https://www.pokemon-card.com/assets/images/card_images/large/M1S/047847_P_MGARURAEX.jpg",
    builtin: true,
  },
  {
    key: "midori",
    label: "みどりのまい (1枚)",
    short: "緑1",
    mode: "draw",
    draw: 1,
    compress: 0,
    description: "山札を1枚引く",
    imageUrl: "https://www.pokemon-card.com/assets/images/card_images/large/MC/048798_P_OGAPONMIDORINOMENEX.jpg",
    builtin: true,
  },
  {
    key: "compress",
    label: "山札圧縮",
    short: "圧",
    mode: "compress",
    draw: 0,
    compress: 1,
    description: "目的カード以外をn枚減らす",
    imageUrl: "https://www.pokemon-card.com/assets/images/card_images/large/XY/037415_T_BATORUKONPURESSAFUREADANGIA.jpg",
    builtin: true,
  },
];
